USE DATABASE WEATHER_DB;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE OR REPLACE TABLE ANALYTICS.WEATHER_CLEAN AS
SELECT
  CITY,
  TO_TIMESTAMP_LTZ(TIMESTAMP) AS reading_time,
  TEMP_C,
  HUMIDITY,
  WEATHER_MAIN,
  RAW
FROM RAW.WEATHER_RAW
WHERE HUMIDITY IS NOT NULL;
